In [11]:
import pandas as pd
import json
import numpy as np
from flask import Flask, jsonify

In [12]:
merged_airports = pd.read_json('Top100Airports_Merged.json')
merged_airports

,Name,data
% Change,Top100 Airports,"{'0': 3.3, '1': 4.5, '2': 5.1, '3': -0.5, '4':..."
Airport,Top100 Airports,"{'0': 'ATLANTA GA, US (ATL)', '1': 'BEIJING, C..."
Airport location,Top100 Airports,"{'0': 'ATLANTA GA, US (ATL) Airport', '1': 'BE..."
CODE,Top100 Airports,"{'0': 'ATL', '1': 'PEK', '2': 'LHR', '3': 'ORD..."
Passengers 2010,Top100 Airports,"{'0': 89292748, '1': 73913402, '2': 65884143, ..."
Passengers 2011,Top100 Airports,"{'0': 92365860, '1': 77403668, '2': 69433565, ..."
RANK,Top100 Airports,"{'0': 1, '1': 2, '2': 3, '3': 4, '4': 5, '5': ..."
REG,Top100 Airports,"{'0': 'NAM', '1': 'ASP', '2': 'EUR', '3': 'NAM..."
carriers,Top100 Airports,"{'0': '60', '1': '84', '2': '105', '3': '85', ..."
city,Top100 Airports,"{'0': 'Atlanta', '1': 'Shunyi', '2': 'Hounslow..."
country,Top100 Airports,"{'0': 'United States', '1': 'China', '2': 'Uni..."
direct_flights,Top100 Airports,"{'0': '253', '1': '165', '2': '227', '3': '222..."
elev,Top100 Airports,"{'0': '1026', '1': '115', '2': '80', '3': '668..."
email,Top100 Airports,"{'0': '', '1': '', '2': '', '3': '', '4': '', ..."
icao,Top100 Airports,"{'0': 'KATL', '1': 'ZBAA', '2': 'EGLL', '3': '..."
lat,Top100 Airports,"{'0': '33.6558', '1': '40.0724', '2': '51.4703..."
lon,Top100 Airports,"{'0': '-84.4333', '1': '116.583', '2': '-0.453..."
name,Top100 Airports,{'0': 'Hartsfield-Jackson Atlanta Internationa...
phone,Top100 Airports,"{'0': '(654) 57 8833', '1': '', '2': '+44 (0)8..."
runway_length,Top100 Airports,"{'0': '11889', '1': '12467', '2': '12802', '3'..."
state,Top100 Airports,"{'0': 'Georgia', '1': 'Beijing', '2': 'England..."
type,Top100 Airports,"{'0': 'Airports', '1': 'Airports', '2': 'Airpo..."
tz,Top100 Airports,"{'0': 'America/New_York', '1': 'Asia/Shanghai'..."
url,Top100 Airports,"{'0': 'http://www.atlanta-airport.com/', '1': ..."
woeid,Top100 Airports,"{'0': '12522118', '1': '12511989', '2': '23382..."

In [54]:
#from json convert into DF
ranks_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    ranks_list = list(data["data"]["RANK"].values())
    

##print(ranks_list)
ranks_list = pd.DataFrame({"RANK":ranks_list})
ranks_list = ranks_list.reset_index()

#from DF convert into Array
ranks_list = ranks_list.values
ranks_list

array([[  0,   1],
       [  1,   2],
       [  2,   3],
       [  3,   4],
       [  4,   5],
       [  5,   6],
       [  6,   7],
       [  7,   8],
       [  8,   9],
       [  9,  10],
       [ 10,  11],
       [ 11,  12],
       [ 12,  13],
       [ 13,  14],
       [ 14,  15],
       [ 15,  16],
       [ 16,  17],
       [ 17,  18],
       [ 18,  19],
       [ 19,  20],
       [ 20,  21],
       [ 21,  22],
       [ 22,  23],
       [ 23,  24],
       [ 24,  25],
       [ 25,  26],
       [ 26,  27],
       [ 27,  28],
       [ 28,  29],
       [ 29,  30],
       [ 30,  31],
       [ 31,  32],
       [ 32,  33],
       [ 33,  34],
       [ 34,  35],
       [ 35,  36],
       [ 36,  37],
       [ 37,  38],
       [ 38,  39],
       [ 39,  40],
       [ 40,  41],
       [ 41,  42],
       [ 42,  43],
       [ 43,  44],
       [ 44,  45],
       [ 45,  46],
       [ 46,  47],
       [ 47,  48],
       [ 48,  49],
       [ 49,  50],
       [ 50,  51],
       [ 51,  52],
       [ 52,  53],
       [ 53,  54],
       [ 54,  55],
       [ 55,  56],
       [ 56,  57],
       [ 57,  58],
       [ 58,  59],
       [ 59,  60],
       [ 60,  61],
       [ 61,  62],
       [ 62,  63],
       [ 63,  64],
       [ 64,  65],
       [ 65,  66],
       [ 66,  67],
       [ 67,  68],
       [ 68,  69],
       [ 69,  70],
       [ 70,  71],
       [ 71,  72],
       [ 72,  73],
       [ 73,  74],
       [ 74,  75],
       [ 75,  76],
       [ 76,  77],
       [ 77,  78],
       [ 78,  79],
       [ 79,  80],
       [ 80,  81],
       [ 81,  82],
       [ 82,  83],
       [ 83,  84],
       [ 84,  85],
       [ 85,  86],
       [ 86,  87],
       [ 87,  88],
       [ 88,  89],
       [ 89,  90],
       [ 90,  91],
       [ 91,  92],
       [ 92,  93],
       [ 93,  94],
       [ 94,  95],
       [ 95,  96],
       [ 96,  97],
       [ 97,  98],
       [ 98,  99],
       [ 99, 100]], dtype=int64)

In [56]:
app = Flask(__name__)
@app.route("/ranks-list")
def ranks_list():
    return jsonify(ranks_list)

if __name__ == "__main__":
    app.run(debug=False)

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [05/Aug/2018 02:08:48] "GET / HTTP/1.1" 404 -

In [52]:
%tb

SystemExit: 1

In [105]:
Airport_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    Airport_list = list(data["data"]["Airport"].values())
    

##print(Airport_list)
Airport_list = pd.DataFrame({"Airport":Airport_list})
Airport_list = Airport_list.reset_index()

#from DF convert into Array
Airport_list = Airport_list.values
Airport_list

array([[0, 'ATLANTA GA, US (ATL)'],
       [1, 'BEIJING, CN (PEK)'],
       [2, 'LONDON, GB (LHR)'],
       [3, 'CHICAGO IL, US (ORD)'],
       [4, 'TOKYO, JP (HND)'],
       [5, 'LOS ANGELES CA, US (LAX)'],
       [6, 'PARIS, FR (CDG)'],
       [7, 'DALLAS/FORT WORTH TX, US (DFW)'],
       [8, 'FRANKFURT, DE (FRA)'],
       [9, 'HONG KONG, HK (HKG)'],
       [10, 'DENVER CO, US (DEN)'],
       [11, 'DUBAI, AE (DXB)'],
       [12, 'JAKARTA, ID (CGK)'],
       [13, 'AMSTERDAM, NL (AMS)'],
       [14, 'MADRID, ES (MAD)'],
       [15, 'BANGKOK, TH (BKK)'],
       [16, 'NEW YORK NY, US (JFK)'],
       [17, 'SINGAPORE, SG (SIN)'],
       [18, 'GUANGZHOU, CN (CAN)'],
       [19, 'LAS VEGAS NV, US (LAS)'],
       [20, 'SHANGHAI, CN (PVG)'],
       [21, 'SAN FRANCISCO CA, US (SFO)'],
       [22, 'PHOENIX AZ, US (PHX)'],
       [23, 'HOUSTON TX, US (IAH)'],
       [24, 'CHARLOTTE NC, US (CLT)'],
       [25, 'MIAMI FL, US (MIA)'],
       [26, 'MUNICH, DE (MUC)'],
       [27, 'KUALA LUMPUR, MY (KUL)'],
       [28, 'ROME, IT (FCO)'],
       [29, 'ISTANBUL, TR (IST)'],
       [30, 'SYDNEY, AU (SYD)'],
       [31, 'ORLANDO FL, US (MCO)'],
       [32, 'INCHEON, KR (ICN)'],
       [33, 'NEW DELHI, IN (DEL)'],
       [34, 'BARCELONA, ES (BCN)'],
       [35, 'LONDON, GB (LGW)'],
       [36, 'NEWARK NJ, US (EWR)'],
       [37, 'TORONTO ON, CA (YYZ)'],
       [38, 'SHANGHAI, CN (SHA)'],
       [39, 'MINNEAPOLIS MN, US (MSP)'],
       [40, 'SEATTLE WA, US (SEA)'],
       [41, 'DETROIT MI, US (DTW)'],
       [42, 'PHILADELPHIA PA, US (PHL)'],
       [43, 'MUMBAI, IN (BOM)'],
       [44, 'SÃO PAULO, BR (GRU)'],
       [45, 'MANILA, PH (MNL)'],
       [46, 'CHENGDU, CN (CTU)'],
       [47, 'BOSTON MA, US (BOS)'],
       [48, 'SHENZHEN, CN (SZX)'],
       [49, 'MELBOURNE, AU (MEL)'],
       [50, 'TOKYO, JP (NRT)'],
       [51, 'PARIS, FR (ORY)'],
       [52, 'MEXICO CITY, MX (MEX)'],
       [53, 'MOSCOW, RU (DME)'],
       [54, 'ANTALYA, TR (AYT)'],
       [55, 'TAIPEI, TW (TPE)'],
       [56, 'ZURICH, CH (ZRH)'],
       [57, 'NEW YORK NY, US (LGA)'],
       [58, 'FORT LAUDERDALE, FL, US (FLL)'],
       [59, 'WASHINGTON, DC, US (IAD)'],
       [60, 'PALMA DE MALLORCA, ES (PMI)'],
       [61, 'COPENHAGEN, DK (CPH)'],
       [62, 'MOSCOW, RU (SVO)'],
       [63, 'BALTIMORE MD, US (BWI)'],
       [64, 'KUNMING, CN (KMG)'],
       [65, 'VIENNA, AT (VIE)'],
       [66, 'OSLO, NO (OSL)'],
       [67, 'JEDDAH, SA (JED)'],
       [68, 'BRISBANE, AU (BNE)'],
       [69, 'SALT LAKE CITY UT, US (SLC)'],
       [70, 'DÜSSELDORF, DE (DUS)'],
       [71, 'BOGOTA, CO (BOG)'],
       [72, 'MILAN, IT (MXP)'],
       [73, 'JOHANNESBURG, ZA (JNB)'],
       [74, 'STOCKHOLM, SE (ARN)'],
       [75, 'MANCHESTER, GB (MAN)'],
       [76, 'CHICAGO IL, US (MDW)'],
       [77, 'WASHINGTON DC, US (DCA)'],
       [78, 'BRUSSELS, BE (BRU)'],
       [79, 'DUBLIN, IE (DUB)'],
       [80, 'SEOUL, KR (GMP)'],
       [81, 'DOHA, QA (DOH)'],
       [82, 'LONDON, GB (STN)'],
       [83, 'HANGZHOU, CN (HGH)'],
       [84, 'JEJU, KR (CJU)'],
       [85, 'VANCOUVER BC, CA (YVR)'],
       [86, 'BERLIN, DE (TXL)'],
       [87, 'SAN DIEGO CA, US (SAN)'],
       [88, 'TAMPA FL, US (TPA)'],
       [89, 'SÃO PAULO, BR (CGH)'],
       [90, 'BRASILIA, BR (BSB)'],
       [91, 'SAPPORO, JP (CTS)'],
       [92, 'XIAMEN, CN (XMN)'],
       [93, 'RIYADH, SA (RUH)'],
       [94, 'FUKUOKA, JP (FUK)'],
       [95, 'RIO DE JANEIRO, BR (GIG)'],
       [96, 'HELSINKI, FI (HEL)'],
       [97, 'LISBON, PT (LIS)'],
       [98, 'ATHENS, GR (ATH)'],
       [99, 'AUCKLAND, NZ (AKL)']], dtype=object)

In [106]:
REG_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    REG_list = list(data["data"]["REG"].values())
    

##print(REG_list)
REG_list = pd.DataFrame({"REG":REG_list})
REG_list = REG_list.reset_index()

#from DF convert into Array
REG_list = REG_list.values
REG_list

array([[0, 'NAM'],
       [1, 'ASP'],
       [2, 'EUR'],
       [3, 'NAM'],
       [4, 'ASP'],
       [5, 'NAM'],
       [6, 'EUR'],
       [7, 'NAM'],
       [8, 'EUR'],
       [9, 'ASP'],
       [10, 'NAM'],
       [11, 'MEA'],
       [12, 'ASP'],
       [13, 'EUR'],
       [14, 'EUR'],
       [15, 'ASP'],
       [16, 'NAM'],
       [17, 'ASP'],
       [18, 'ASP'],
       [19, 'NAM'],
       [20, 'ASP'],
       [21, 'NAM'],
       [22, 'NAM'],
       [23, 'NAM'],
       [24, 'NAM'],
       [25, 'NAM'],
       [26, 'EUR'],
       [27, 'ASP'],
       [28, 'EUR'],
       [29, 'EUR'],
       [30, 'ASP'],
       [31, 'NAM'],
       [32, 'ASP'],
       [33, 'ASP'],
       [34, 'EUR'],
       [35, 'EUR'],
       [36, 'NAM'],
       [37, 'NAM'],
       [38, 'ASP'],
       [39, 'NAM'],
       [40, 'NAM'],
       [41, 'NAM'],
       [42, 'NAM'],
       [43, 'ASP'],
       [44, 'LAC'],
       [45, 'ASP'],
       [46, 'ASP'],
       [47, 'NAM'],
       [48, 'ASP'],
       [49, 'ASP'],
       [50, 'ASP'],
       [51, 'EUR'],
       [52, 'LAC'],
       [53, 'EUR'],
       [54, 'EUR'],
       [55, 'ASP'],
       [56, 'EUR'],
       [57, 'NAM'],
       [58, 'NAM'],
       [59, 'NAM'],
       [60, 'EUR'],
       [61, 'EUR'],
       [62, 'EUR'],
       [63, 'NAM'],
       [64, 'ASP'],
       [65, 'EUR'],
       [66, 'EUR'],
       [67, 'MEA'],
       [68, 'ASP'],
       [69, 'NAM'],
       [70, 'EUR'],
       [71, 'LAC'],
       [72, 'EUR'],
       [73, 'AFR'],
       [74, 'EUR'],
       [75, 'EUR'],
       [76, 'NAM'],
       [77, 'NAM'],
       [78, 'EUR'],
       [79, 'EUR'],
       [80, 'ASP'],
       [81, 'MEA'],
       [82, 'EUR'],
       [83, 'ASP'],
       [84, 'ASP'],
       [85, 'NAM'],
       [86, 'EUR'],
       [87, 'NAM'],
       [88, 'NAM'],
       [89, 'LAC'],
       [90, 'LAC'],
       [91, 'ASP'],
       [92, 'ASP'],
       [93, 'MEA'],
       [94, 'ASP'],
       [95, 'LAC'],
       [96, 'EUR'],
       [97, 'EUR'],
       [98, 'EUR'],
       [99, 'ASP']], dtype=object)

In [107]:
carriers_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    carriers_list = list(data["data"]["carriers"].values())
    

##print(carriers_list)
carriers_list = pd.DataFrame({"carriers":carriers_list})
carriers_list = carriers_list.reset_index()

#from DF convert into Array
carriers_list = carriers_list.values
carriers_list

array([[0, '60'],
       [1, '84'],
       [2, '105'],
       [3, '85'],
       [4, '19'],
       [5, '99'],
       [6, '131'],
       [7, '62'],
       [8, '131'],
       [9, '87'],
       [10, '57'],
       [11, '126'],
       [12, '45'],
       [13, '118'],
       [14, '93'],
       [15, '113'],
       [16, '100'],
       [17, '80'],
       [18, '49'],
       [19, '64'],
       [20, '76'],
       [21, '76'],
       [22, '51'],
       [23, '54'],
       [24, '39'],
       [25, '91'],
       [26, '95'],
       [27, '68'],
       [28, '124'],
       [29, '79'],
       [30, '55'],
       [31, '63'],
       [32, '76'],
       [33, '70'],
       [34, '90'],
       [35, '71'],
       [36, '64'],
       [37, '66'],
       [38, '21'],
       [39, '41'],
       [40, '59'],
       [41, '45'],
       [42, '51'],
       [43, '60'],
       [44, '35'],
       [45, '35'],
       [46, '30'],
       [47, '68'],
       [48, '31'],
       [49, '44'],
       [50, '63'],
       [51, '52'],
       [52, '42'],
       [53, '71'],
       [54, '24'],
       [55, '43'],
       [56, '79'],
       [57, '30'],
       [58, '46'],
       [59, '63'],
       [60, '57'],
       [61, '76'],
       [62, '48'],
       [63, '39'],
       [64, '27'],
       [65, '96'],
       [66, '59'],
       [67, '54'],
       [68, '43'],
       [69, '38'],
       [70, '74'],
       [71, '30'],
       [72, '109'],
       [73, '63'],
       [74, '76'],
       [75, '79'],
       [76, '8'],
       [77, '42'],
       [78, '97'],
       [79, '54'],
       [80, '9'],
       [81, '43'],
       [82, '25'],
       [83, '28'],
       [84, '8'],
       [85, '54'],
       [86, '70'],
       [87, '57'],
       [88, '48'],
       [89, '6'],
       [90, '10'],
       [91, '28'],
       [92, '33'],
       [93, '35'],
       [94, '31'],
       [95, '25'],
       [96, '53'],
       [97, '57'],
       [98, '81'],
       [99, '35']], dtype=object)

In [108]:
city_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    city_list = list(data["data"]["city"].values())
    

##print(carriers_list)
city_list = pd.DataFrame({"city":city_list})
city_list = city_list.reset_index()

#from DF convert into Array
city_list = city_list.values
city_list

array([[0, 'Atlanta'],
       [1, 'Shunyi'],
       [2, 'Hounslow'],
       [3, 'Chicago'],
       [4, 'Tokyo'],
       [5, 'Los Angeles'],
       [6, 'Le Mesnil-Amelot'],
       [7, 'Dallas'],
       [8, 'Frankfurt'],
       [9, 'Hong Kong'],
       [10, 'Denver'],
       [11, 'Dubai'],
       [12, 'Tangerang'],
       [13, 'Schiphol Zuid'],
       [14, 'Madrid'],
       [15, 'Lak Si'],
       [16, 'Jamaica'],
       [17, 'Singapore'],
       [18, 'Guangzhou'],
       [19, 'Las Vegas'],
       [20, 'Huinan'],
       [21, 'San Francisco'],
       [22, 'Phoenix'],
       [23, 'Houston'],
       [24, 'Charlotte'],
       [25, 'Miami'],
       [26, 'Oberding'],
       [27, 'Sepang'],
       [28, 'Rome'],
       [29, 'Bakırköy'],
       [30, 'Sydney'],
       [31, 'Orlando'],
       [32, 'Incheon'],
       [33, 'New Delhi'],
       [34, 'El Prat de Llobregat'],
       [35, 'Horley'],
       [36, 'Newark'],
       [37, 'Mississauga'],
       [38, 'Shanghai'],
       [39, 'St. Paul'],
       [40, 'Seattle'],
       [41, 'Detroit'],
       [42, 'Philadelphia'],
       [43, 'Mumbai'],
       [44, 'Guarulhos'],
       [45, 'Parañaque'],
       [46, 'Chengdu'],
       [47, 'Boston'],
       [48, 'Shenzhen'],
       [49, 'Melbourne'],
       [50, 'Narita-shi'],
       [51, 'Paris'],
       [52, 'Mexico City'],
       [53, "Podol'sk"],
       [54, 'Antalya'],
       [55, 'Taoyuan City'],
       [56, 'Kloten'],
       [57, 'Flushing'],
       [58, 'Dania Beach'],
       [59, 'Washington'],
       [60, 'Palma'],
       [61, 'Kastrup'],
       [62, 'Zelenograd'],
       [63, 'Baltimore'],
       [64, 'Kunming'],
       [65, 'Klein-Neusiedl'],
       [66, 'Gardermoen'],
       [67, 'Jeddah'],
       [68, 'Brisbane'],
       [69, 'Salt Lake City'],
       [70, 'Dusseldorf'],
       [71, 'Fontibón'],
       [72, 'Cardano al Campo'],
       [73, 'Johannesburg'],
       [74, 'Märst'],
       [75, 'Manchester'],
       [76, 'Chicago'],
       [77, 'Arlington'],
       [78, 'Bruxelles'],
       [79, 'Cloghran'],
       [80, 'Seoul'],
       [81, 'Doha'],
       [82, 'Stansted Mountfitchet'],
       [83, 'Hangzhou'],
       [84, 'Jeju-Si'],
       [85, 'Richmond'],
       [86, 'Berlin'],
       [87, 'San Diego'],
       [88, 'Tampa'],
       [89, 'Sao Paulo'],
       [90, 'Lago Sul'],
       [91, 'Chitose-shi'],
       [92, 'Xiamen'],
       [93, 'Riyadh'],
       [94, 'Fukuoka-shi'],
       [95, 'Rio de Janeiro'],
       [96, 'Vantaa'],
       [97, 'Lisbon'],
       [98, 'Athens'],
       [99, 'Manukau City']], dtype=object)

In [109]:
country_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    country_list = list(data["data"]["country"].values())
    

##print(country_list)
country_list = pd.DataFrame({"country":country_list})
country_list = country_list.reset_index()

#from DF convert into Array
country_list = country_list.values
country_list

array([[0, 'United States'],
       [1, 'China'],
       [2, 'United Kingdom'],
       [3, 'United States'],
       [4, 'Japan'],
       [5, 'United States'],
       [6, 'France'],
       [7, 'United States'],
       [8, 'Germany'],
       [9, 'Hong Kong'],
       [10, 'United States'],
       [11, 'United Arab Emirates'],
       [12, 'Indonesia'],
       [13, 'Netherlands'],
       [14, 'Spain'],
       [15, 'Thailand'],
       [16, 'United States'],
       [17, 'Singapore'],
       [18, 'China'],
       [19, 'United States'],
       [20, 'China'],
       [21, 'United States'],
       [22, 'United States'],
       [23, 'United States'],
       [24, 'United States'],
       [25, 'United States'],
       [26, 'Germany'],
       [27, 'Malaysia'],
       [28, 'Italy'],
       [29, 'Turkey'],
       [30, 'Australia'],
       [31, 'United States'],
       [32, 'South Korea'],
       [33, 'India'],
       [34, 'Spain'],
       [35, 'United Kingdom'],
       [36, 'United States'],
       [37, 'Canada'],
       [38, 'China'],
       [39, 'United States'],
       [40, 'United States'],
       [41, 'United States'],
       [42, 'United States'],
       [43, 'India'],
       [44, 'Brazil'],
       [45, 'Philippines'],
       [46, 'China'],
       [47, 'United States'],
       [48, 'China'],
       [49, 'Australia'],
       [50, 'Japan'],
       [51, 'France'],
       [52, 'Mexico'],
       [53, 'Russia'],
       [54, 'Turkey'],
       [55, 'Taiwan'],
       [56, 'Switzerland'],
       [57, 'United States'],
       [58, 'United States'],
       [59, 'United States'],
       [60, 'Spain'],
       [61, 'Denmark'],
       [62, 'Russia'],
       [63, 'United States'],
       [64, 'China'],
       [65, 'Austria'],
       [66, 'Norway'],
       [67, 'Saudi Arabia'],
       [68, 'Australia'],
       [69, 'United States'],
       [70, 'Germany'],
       [71, 'Colombia'],
       [72, 'Italy'],
       [73, 'South Africa'],
       [74, 'Sweden'],
       [75, 'United Kingdom'],
       [76, 'United States'],
       [77, 'United States'],
       [78, 'Belgium'],
       [79, 'Ireland'],
       [80, 'South Korea'],
       [81, 'Qatar'],
       [82, 'United Kingdom'],
       [83, 'China'],
       [84, 'South Korea'],
       [85, 'Canada'],
       [86, 'Germany'],
       [87, 'United States'],
       [88, 'United States'],
       [89, 'Brazil'],
       [90, 'Brazil'],
       [91, 'Japan'],
       [92, 'China'],
       [93, 'Saudi Arabia'],
       [94, 'Japan'],
       [95, 'Brazil'],
       [96, 'Finland'],
       [97, 'Portugal'],
       [98, 'Greece'],
       [99, 'New Zealand']], dtype=object)

In [110]:
direct_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    direct_list = list(data["data"]["direct_flights"].values())
    

##print(direct_list)
direct_list = pd.DataFrame({"direct_flights":direct_list})
direct_list = direct_list.reset_index()

#from DF convert into Array
direct_list = direct_list.values
direct_list

array([[0, '253'],
       [1, '165'],
       [2, '227'],
       [3, '222'],
       [4, '55'],
       [5, '200'],
       [6, '310'],
       [7, '179'],
       [8, '337'],
       [9, '131'],
       [10, '162'],
       [11, '170'],
       [12, '51'],
       [13, '284'],
       [14, '186'],
       [15, '132'],
       [16, '233'],
       [17, '108'],
       [18, '111'],
       [19, '130'],
       [20, '131'],
       [21, '147'],
       [22, '108'],
       [23, '210'],
       [24, '133'],
       [25, '167'],
       [26, '213'],
       [27, '101'],
       [28, '181'],
       [29, '157'],
       [30, '84'],
       [31, '106'],
       [32, '139'],
       [33, '95'],
       [34, '145'],
       [35, '227'],
       [36, '220'],
       [37, '176'],
       [38, '60'],
       [39, '171'],
       [40, '109'],
       [41, '161'],
       [42, '133'],
       [43, '86'],
       [44, '63'],
       [45, '77'],
       [46, '62'],
       [47, '113'],
       [48, '81'],
       [49, '53'],
       [50, '97'],
       [51, '138'],
       [52, '98'],
       [53, '165'],
       [54, '51'],
       [55, '52'],
       [56, '161'],
       [57, '82'],
       [58, '108'],
       [59, '150'],
       [60, '109'],
       [61, '136'],
       [62, '140'],
       [63, '79'],
       [64, '62'],
       [65, '183'],
       [66, '116'],
       [67, '106'],
       [68, '62'],
       [69, '104'],
       [70, '167'],
       [71, '64'],
       [72, '163'],
       [73, '89'],
       [74, '126'],
       [75, '129'],
       [76, '55'],
       [77, '77'],
       [78, '186'],
       [79, '167'],
       [80, '10'],
       [81, '87'],
       [82, '168'],
       [83, '46'],
       [84, '19'],
       [85, '92'],
       [86, '101'],
       [87, '51'],
       [88, '74'],
       [89, '26'],
       [90, '32'],
       [91, '30'],
       [92, '55'],
       [93, '71'],
       [94, '36'],
       [95, '32'],
       [96, '104'],
       [97, '92'],
       [98, '117'],
       [99, '52']], dtype=object)

In [133]:
lat_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    lat_list = list(data["data"]["lat"].values())
    

##print(lat_list)
lat_list = pd.DataFrame({"lat":lat_list})
#lat_list = lat_list.reset_index()

#from DF convert into Array
lat_list = lat_list.values
lat_list

array([['33.6558'],
       ['40.0724'],
       ['51.4703'],
       ['41.9796'],
       ['35.5533'],
       ['33.9456'],
       ['49.0175'],
       ['32.9222'],
       ['50.0483'],
       ['22.3124'],
       ['39.8396'],
       ['25.2509'],
       ['-6.11964'],
       ['52.3122'],
       ['40.4684'],
       ['13.9144'],
       ['40.6437'],
       ['1.3578'],
       ['23.3925'],
       ['36.0806'],
       ['31.1156'],
       ['37.6148'],
       ['33.4376'],
       ['29.9784'],
       ['35.2226'],
       ['25.7953'],
       ['48.354'],
       ['2.77859'],
       ['41.8026'],
       ['40.9857'],
       ['-33.9344'],
       ['28.4418'],
       ['37.4534'],
       ['28.5603'],
       ['41.3006'],
       ['51.1568'],
       ['40.6924'],
       ['43.685'],
       ['31.1865'],
       ['44.8793'],
       ['47.4405'],
       ['42.2327'],
       ['39.8768'],
       ['19.0932'],
       ['-23.435'],
       ['14.5114'],
       ['30.5775'],
       ['42.3717'],
       ['22.5333'],
       ['-37.6759'],
       ['35.7491'],
       ['48.7261'],
       ['19.4344'],
       ['55.4025'],
       ['36.9022'],
       ['25.081'],
       ['47.454'],
       ['40.7731'],
       ['26.0722'],
       ['38.9556'],
       ['39.5495'],
       ['55.6205'],
       ['55.9621'],
       ['39.1841'],
       ['24.966'],
       ['48.1036'],
       ['60.1947'],
       ['21.706'],
       ['-27.3589'],
       ['40.7862'],
       ['51.2794'],
       ['4.69895'],
       ['45.6314'],
       ['-26.1219'],
       ['59.6521'],
       ['53.365'],
       ['41.7875'],
       ['38.849'],
       ['50.899'],
       ['53.4272'],
       ['37.5563'],
       ['25.2592'],
       ['51.8894'],
       ['30.3332'],
       ['33.5056'],
       ['49.1931'],
       ['52.5548'],
       ['32.7299'],
       ['27.9744'],
       ['-23.6285'],
       ['-15.8622'],
       ['42.7757'],
       ['24.5333'],
       ['24.9625'],
       ['33.5971'],
       ['-22.8094'],
       ['60.3243'],
       ['38.7701'],
       ['37.8937'],
       ['-37.0085']], dtype=object)

In [132]:
lon_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    lon_list = list(data["data"]["lon"].values())
    

##print(lon_list)
lon_list = pd.DataFrame({"lon":lon_list})
#lon_list = lon_list.reset_index()

#from DF convert into Array
lon_list = lon_list.values
lon_list

array([['-84.4333'],
       ['116.583'],
       ['-0.45342'],
       ['-87.8825'],
       ['139.771'],
       ['-118.391'],
       ['2.5564'],
       ['-97.0409'],
       ['8.57041'],
       ['113.929'],
       ['-104.672'],
       ['55.3629'],
       ['106.656'],
       ['4.77511'],
       ['-3.56769'],
       ['100.608'],
       ['-73.79'],
       ['103.991'],
       ['113.299'],
       ['-115.143'],
       ['121.803'],
       ['-122.392'],
       ['-112.03'],
       ['-95.3424'],
       ['-80.946'],
       ['-80.2727'],
       ['11.7816'],
       ['101.689'],
       ['12.2551'],
       ['28.8163'],
       ['151.168'],
       ['-81.3115'],
       ['126.657'],
       ['77.1027'],
       ['2.07976'],
       ['-0.16988'],
       ['-74.1843'],
       ['-79.6142'],
       ['121.34'],
       ['-93.1987'],
       ['-122.296'],
       ['-83.3412'],
       ['-75.2419'],
       ['72.8654'],
       ['-46.4728'],
       ['121.016'],
       ['103.941'],
       ['-71.0281'],
       ['113.967'],
       ['144.844'],
       ['140.389'],
       ['2.36411'],
       ['-99.0742'],
       ['37.9136'],
       ['30.7917'],
       ['121.237'],
       ['8.56137'],
       ['-73.8756'],
       ['-80.1354'],
       ['-77.4484'],
       ['2.73188'],
       ['12.6495'],
       ['37.4189'],
       ['-76.6745'],
       ['102.733'],
       ['16.5804'],
       ['11.1005'],
       ['39.1386'],
       ['153.122'],
       ['-111.982'],
       ['6.76481'],
       ['-74.1435'],
       ['8.72284'],
       ['28.2467'],
       ['17.9317'],
       ['-2.27089'],
       ['-87.7416'],
       ['-77.0438'],
       ['4.4859'],
       ['-6.24418'],
       ['126.793'],
       ['51.5658'],
       ['0.26151'],
       ['120.234'],
       ['126.495'],
       ['-123.172'],
       ['13.289'],
       ['-117.195'],
       ['-82.5356'],
       ['-46.6589'],
       ['-47.9122'],
       ['141.691'],
       ['118.117'],
       ['46.7078'],
       ['130.443'],
       ['-43.25'],
       ['24.9688'],
       ['-9.13775'],
       ['23.7235'],
       ['174.782']], dtype=object)

In [145]:
coordinates = np.concatenate((lat_list, lon_list), axis=1)
coordinates = pd.DataFrame.from_dict(coordinates)
coordinates = coordinates.reset_index()
coordinates = coordinates.values
coordinates

array([[0, '33.6558', '-84.4333'],
       [1, '40.0724', '116.583'],
       [2, '51.4703', '-0.45342'],
       [3, '41.9796', '-87.8825'],
       [4, '35.5533', '139.771'],
       [5, '33.9456', '-118.391'],
       [6, '49.0175', '2.5564'],
       [7, '32.9222', '-97.0409'],
       [8, '50.0483', '8.57041'],
       [9, '22.3124', '113.929'],
       [10, '39.8396', '-104.672'],
       [11, '25.2509', '55.3629'],
       [12, '-6.11964', '106.656'],
       [13, '52.3122', '4.77511'],
       [14, '40.4684', '-3.56769'],
       [15, '13.9144', '100.608'],
       [16, '40.6437', '-73.79'],
       [17, '1.3578', '103.991'],
       [18, '23.3925', '113.299'],
       [19, '36.0806', '-115.143'],
       [20, '31.1156', '121.803'],
       [21, '37.6148', '-122.392'],
       [22, '33.4376', '-112.03'],
       [23, '29.9784', '-95.3424'],
       [24, '35.2226', '-80.946'],
       [25, '25.7953', '-80.2727'],
       [26, '48.354', '11.7816'],
       [27, '2.77859', '101.689'],
       [28, '41.8026', '12.2551'],
       [29, '40.9857', '28.8163'],
       [30, '-33.9344', '151.168'],
       [31, '28.4418', '-81.3115'],
       [32, '37.4534', '126.657'],
       [33, '28.5603', '77.1027'],
       [34, '41.3006', '2.07976'],
       [35, '51.1568', '-0.16988'],
       [36, '40.6924', '-74.1843'],
       [37, '43.685', '-79.6142'],
       [38, '31.1865', '121.34'],
       [39, '44.8793', '-93.1987'],
       [40, '47.4405', '-122.296'],
       [41, '42.2327', '-83.3412'],
       [42, '39.8768', '-75.2419'],
       [43, '19.0932', '72.8654'],
       [44, '-23.435', '-46.4728'],
       [45, '14.5114', '121.016'],
       [46, '30.5775', '103.941'],
       [47, '42.3717', '-71.0281'],
       [48, '22.5333', '113.967'],
       [49, '-37.6759', '144.844'],
       [50, '35.7491', '140.389'],
       [51, '48.7261', '2.36411'],
       [52, '19.4344', '-99.0742'],
       [53, '55.4025', '37.9136'],
       [54, '36.9022', '30.7917'],
       [55, '25.081', '121.237'],
       [56, '47.454', '8.56137'],
       [57, '40.7731', '-73.8756'],
       [58, '26.0722', '-80.1354'],
       [59, '38.9556', '-77.4484'],
       [60, '39.5495', '2.73188'],
       [61, '55.6205', '12.6495'],
       [62, '55.9621', '37.4189'],
       [63, '39.1841', '-76.6745'],
       [64, '24.966', '102.733'],
       [65, '48.1036', '16.5804'],
       [66, '60.1947', '11.1005'],
       [67, '21.706', '39.1386'],
       [68, '-27.3589', '153.122'],
       [69, '40.7862', '-111.982'],
       [70, '51.2794', '6.76481'],
       [71, '4.69895', '-74.1435'],
       [72, '45.6314', '8.72284'],
       [73, '-26.1219', '28.2467'],
       [74, '59.6521', '17.9317'],
       [75, '53.365', '-2.27089'],
       [76, '41.7875', '-87.7416'],
       [77, '38.849', '-77.0438'],
       [78, '50.899', '4.4859'],
       [79, '53.4272', '-6.24418'],
       [80, '37.5563', '126.793'],
       [81, '25.2592', '51.5658'],
       [82, '51.8894', '0.26151'],
       [83, '30.3332', '120.234'],
       [84, '33.5056', '126.495'],
       [85, '49.1931', '-123.172'],
       [86, '52.5548', '13.289'],
       [87, '32.7299', '-117.195'],
       [88, '27.9744', '-82.5356'],
       [89, '-23.6285', '-46.6589'],
       [90, '-15.8622', '-47.9122'],
       [91, '42.7757', '141.691'],
       [92, '24.5333', '118.117'],
       [93, '24.9625', '46.7078'],
       [94, '33.5971', '130.443'],
       [95, '-22.8094', '-43.25'],
       [96, '60.3243', '24.9688'],
       [97, '38.7701', '-9.13775'],
       [98, '37.8937', '23.7235'],
       [99, '-37.0085', '174.782']], dtype=object)

In [113]:
name_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    name_list = list(data["data"]["name"].values())
    

##print(name_list)
name_list = pd.DataFrame({"name":name_list})
name_list = name_list.reset_index()

#from DF convert into Array
name_list = name_list.values
name_list

array([[0, 'Hartsfield-Jackson Atlanta International Airport'],
       [1, 'Beijing Capital Airport'],
       [2, 'London Heathrow Airport'],
       [3, "Chicago O'Hare International Airport"],
       [4, 'Tokyo International Airport'],
       [5, 'Los Angeles International Airport'],
       [6, 'Charles de Gaulle International Airport'],
       [7, 'Fort Worth International Airport'],
       [8, 'Frankfurt International Airport'],
       [9, 'Hong Kong International Airport'],
       [10, 'Denver International Airport'],
       [11, 'Dubai International Airport'],
       [12, 'Jakarta International Airport'],
       [13, 'Schiphol Airport'],
       [14, 'Barajas Airport'],
       [15, 'Bangkok International Airport'],
       [16, 'John F Kennedy International Airport'],
       [17, 'Singapore Changi Airport'],
       [18, 'Baiyun Airport'],
       [19, 'Mccarran International Airport'],
       [20, 'Pudong International Airport'],
       [21, 'San Francisco International Airport'],
       [22, 'Sky Harbor International Airport'],
       [23, 'George Bush Intercontinental Airport'],
       [24, 'Douglas International Airport'],
       [25, 'Miami International Airport'],
       [26, 'Franz-Josef-Strauss Airport'],
       [27, 'Kuala Lumpur International Airport'],
       [28, 'Leonardo da Vinci International Airport'],
       [29, 'Ataturk Hava Limani Airport'],
       [30, 'Kingsford Smith Airport'],
       [31, 'Orlando International Airport'],
       [32, 'New Incheon International Airport'],
       [33, 'Indira Gandhi International Airport'],
       [34, 'Barcelona International Airport'],
       [35, 'London Gatwick Airport'],
       [36, 'Newark International Airport'],
       [37, 'Toronto Lester B Pearson International Airport'],
       [38, 'Hongqiao Airport'],
       [39, 'Minneapolis St Paul International Airport'],
       [40, 'Tacoma International Airport'],
       [41, 'Detroit Metropolitan Wayne County Airport'],
       [42, 'Philadelphia International Airport'],
       [43, 'Chhatrapati Shivaji International Airport'],
       [44, 'Governador Andre Franco Montoro International Ai'],
       [45, 'Ninoy Aquino International Airport'],
       [46, 'Chengdushuang Liu Airport'],
       [47, 'Gen E L Logan International Airport'],
       [48, 'Shenzhen Airport'],
       [49, 'Melbourne International Airport'],
       [50, 'Narita International Airport'],
       [51, 'Paris Orly Airport'],
       [52, 'Lic Benito Juarez International Airport'],
       [53, 'Domodedovo Airport'],
       [54, 'Antalya Airport'],
       [55, 'Taiwan Taoyuan International Airport'],
       [56, 'Zurich International Airport'],
       [57, 'LaGuardia Airport'],
       [58, 'Fort Lauderdale Hollywood International Airport'],
       [59, 'Dulles International Airport'],
       [60, 'Palma de Mallorca Airport'],
       [61, 'Copenhagen Airport'],
       [62, 'Sheremtyevo Airport'],
       [63, 'Baltimore-Washington International Thurgood Mars'],
       [64, 'Wuchia Pa Airport'],
       [65, 'Vienna Schwechat International Airport'],
       [66, 'Oslo Gardermoen Airport'],
       [67, 'King Abdul Aziz International Airport'],
       [68, 'Brisbane International Airport'],
       [69, 'Salt Lake City International Airport'],
       [70, 'Dusseldorf International Airport'],
       [71, 'Eldorado International Airport'],
       [72, 'Malpensa International Airport'],
       [73, 'OR Tambo International Airport'],
       [74, 'Arlanda Airport'],
       [75, 'Manchester International Airport'],
       [76, 'Chicago Midway International Airport'],
       [77, 'Washington National Airport'],
       [78, 'Brussels Airport'],
       [79, 'Dublin Airport'],
       [80, 'Gimpo International Airport'],
       [81, 'Doha International Airport'],
       [82, 'London Stansted International Airport'],
       [83, 'Jianoiao Airport'],
       [84, 'Cheju International Airport'],
       [85, 'Vancouver International Airport'],
       [86, 'Berlin-Tegel International Airport'],
       [87, 'San Diego International Airport'],
       [88, 'Tampa International Airport'],
       [89, 'Congonhas International Airport'],
       [90, 'Juscelino Kubitschek International Airport'],
       [91, 'New Chitose Airport'],
       [92, 'Xiamen Airport'],
       [93, 'King Khalid International Airport'],
       [94, 'Fukuoka Airport'],
       [95, 'Rio de Janeiro-Antonio Carlos Jobim Internationa'],
       [96, 'Helsinki Vantaa Airport'],
       [97, 'Lisbon Airport'],
       [98, 'Eleftherios Venizelos International Airport'],
       [99, 'Auckland International Airport']], dtype=object)

In [114]:
url_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    url_list = list(data["data"]["url"].values())
    

##print(url_list)
url_list = pd.DataFrame({"url":url_list})
url_list = url_list.reset_index()

#from DF convert into Array
url_list = url_list.values
url_list

array([[0, 'http://www.atlanta-airport.com/'],
       [1, 'http://www.bcia.com.cn'],
       [2, 'http://www.heathrowairport.com'],
       [3, 'http://www.flychicago.com/ohare/home.asp'],
       [4, 'http://www.tokyo-airport-bldg.co.jp/'],
       [5, ''],
       [6, ''],
       [7, ''],
       [8, 'http://www.airportcity-frankfurt.de'],
       [9, 'http://www.hongkongairport.com/'],
       [10, ''],
       [11, 'http://www.dubaiairport.com'],
       [12, 'http://www.angkasapura2.co.id'],
       [13, 'http://www.schiphol.com/'],
       [14, ''],
       [15, 'http://www.airportthai.co.th/airportnew/bia/html/'],
       [16, ''],
       [17, 'http://www.changiairport.com.sg/'],
       [18, ''],
       [19, 'http://www.mccarran.com'],
       [20, ''],
       [21, 'http://www.flysfo.com'],
       [22, 'http://phoenix.gov/Ahttp://phoenix.gov/aviation'],
       [23, ''],
       [24, 'http://www.charmeck.org/Departments/Airport/Home.htm'],
       [25, 'http://www.miami-airport.com'],
       [26, 'http://www.munich-airport.de/'],
       [27, 'http://www.klia.com.my/'],
       [28, 'http://www.adr.it/'],
       [29, ''],
       [30, ''],
       [31, ''],
       [32, 'http://www.airport.or.kr/eng/airport/'],
       [33, ''],
       [34, 'http://www.aena.es'],
       [35, 'http://www.gatwickairport.com/'],
       [36, ''],
       [37, 'http://www.gtaa.com/'],
       [38, ''],
       [39, 'http://mspairport.com'],
       [40, 'http://www.portseattle.org/seatac/'],
       [41, 'http://www.metroairport.com/'],
       [42, 'http://www.phl.org'],
       [43, 'http://www.airportsindia.org.in/aai/mumbai/index.htm'],
       [44, ''],
       [45, ''],
       [46, 'http://www.cdairport.com/cdairport/en_front/index.jsp'],
       [47, ''],
       [48, 'http://www.szairport.com/index_e.asp'],
       [49, ''],
       [50, 'http://www.narita-airport.jp'],
       [51, 'http://www.adp.fr'],
       [52, 'http://www.aicm.com.mx/'],
       [53, 'http://www.domodedovo.ru'],
       [54, ''],
       [55, 'http://www.cksairport.gov.tw/'],
       [56, 'http://www.zurich-airport.com'],
       [57, ''],
       [58, ''],
       [59, 'http://www.metwashairports.com/Dulles/'],
       [60, ''],
       [61, 'http://www.cph.dk'],
       [62, 'http://www.sheremetyevo-airport.ru'],
       [63, 'http://www.bwiairport.com'],
       [64, ''],
       [65, 'http://www.viennaairport.com'],
       [66, 'http://www.osl.no'],
       [67, ''],
       [68, 'http://www.bne.com.au/'],
       [69, ''],
       [70, 'http://www.duesseldorf-international.de/'],
       [71, 'http://www.aerocivil.gov.co/plan%20maestro/index.htm'],
       [72, 'http://www.sea-aeroportimilano.it/'],
       [73, 'http://www.airports.co.za/home.asp?pid=1147'],
       [74, 'http://www.arlanda.se'],
       [75, 'http://www.manchesterairport.co.uk'],
       [76, ''],
       [77, 'http://metwashairports.com/reagan'],
       [78, 'http://www.brusselsairport.be'],
       [79, 'http://www.dub.aero'],
       [80, ''],
       [81, ''],
       [82, 'http://www.stanstedairport.com/'],
       [83, ''],
       [84, ''],
       [85, 'http://www.yvr.ca/'],
       [86,
        'http://www.berlin-airport.de/PubEnglish/PubTegel/index.php?'],
       [87, 'http://www.san.org/'],
       [88, 'http://www.tampaairport.com/'],
       [89, ''],
       [90, 'http://www.infraero.gov.br/'],
       [91, ''],
       [92, ''],
       [93, ''],
       [94, ''],
       [95, ''],
       [96, 'http://www.helsinki-vantaa.fi/'],
       [97, 'http://www.ana.pt'],
       [98, 'http://www.aia.gr'],
       [99, 'http://www.auckland-airport.co.nz/']], dtype=object)