In [5]:
import pandas as pd
import json
import numpy as np
from flask import Flask, jsonify

In [2]:
merged_airports = pd.read_json('Top100Airports_Merged.json')
merged_airports

,Name,data
% Change,Top100 Airports,"{'0': 3.3, '1': 4.5, '2': 5.1, '3': -0.5, '4':..."
Airport,Top100 Airports,"{'0': 'ATLANTA GA, US (ATL)', '1': 'BEIJING, C..."
Airport location,Top100 Airports,"{'0': 'ATLANTA GA, US (ATL) Airport', '1': 'BE..."
CODE,Top100 Airports,"{'0': 'ATL', '1': 'PEK', '2': 'LHR', '3': 'ORD..."
Passengers 2010,Top100 Airports,"{'0': 89292748, '1': 73913402, '2': 65884143, ..."
Passengers 2011,Top100 Airports,"{'0': 92365860, '1': 77403668, '2': 69433565, ..."
RANK,Top100 Airports,"{'0': 1, '1': 2, '2': 3, '3': 4, '4': 5, '5': ..."
REG,Top100 Airports,"{'0': 'NAM', '1': 'ASP', '2': 'EUR', '3': 'NAM..."
carriers,Top100 Airports,"{'0': '60', '1': '84', '2': '105', '3': '85', ..."
city,Top100 Airports,"{'0': 'Atlanta', '1': 'Shunyi', '2': 'Hounslow..."
country,Top100 Airports,"{'0': 'United States', '1': 'China', '2': 'Uni..."
direct_flights,Top100 Airports,"{'0': '253', '1': '165', '2': '227', '3': '222..."
elev,Top100 Airports,"{'0': '1026', '1': '115', '2': '80', '3': '668..."
email,Top100 Airports,"{'0': '', '1': '', '2': '', '3': '', '4': '', ..."
icao,Top100 Airports,"{'0': 'KATL', '1': 'ZBAA', '2': 'EGLL', '3': '..."
lat,Top100 Airports,"{'0': '33.6558', '1': '40.0724', '2': '51.4703..."
lon,Top100 Airports,"{'0': '-84.4333', '1': '116.583', '2': '-0.453..."
name,Top100 Airports,{'0': 'Hartsfield-Jackson Atlanta Internationa...
phone,Top100 Airports,"{'0': '(654) 57 8833', '1': '', '2': '+44 (0)8..."
runway_length,Top100 Airports,"{'0': '11889', '1': '12467', '2': '12802', '3'..."
state,Top100 Airports,"{'0': 'Georgia', '1': 'Beijing', '2': 'England..."
type,Top100 Airports,"{'0': 'Airports', '1': 'Airports', '2': 'Airpo..."
tz,Top100 Airports,"{'0': 'America/New_York', '1': 'Asia/Shanghai'..."
url,Top100 Airports,"{'0': 'http://www.atlanta-airport.com/', '1': ..."
woeid,Top100 Airports,"{'0': '12522118', '1': '12511989', '2': '23382..."

In [29]:
#from json convert into DF
ranks_list = []

with open('Top100Airports_Merged.json') as json_file:
    data = json.load(json_file)
    ranks_list = list(data["data"]["RANK"].values())
    

##print(ranks_list)
ranks_list = pd.DataFrame({"RANK":ranks_list})
ranks_list = ranks_list.reset_index()

#from DF convert into Array
ranks_list = ranks_list.values

In [36]:
app = Flask(__name__)

@app.route('/_get_current_user')
def get_ranks_list():
    return jsonify(ranks_list)